apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: db-service
    app: demo-voting-app
  name: db
spec: 
 ports:
  - port: 5432
    targetPort: 5432
 selector:
  name: postgres-pod
  app: demo-voting-app  