apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: demo-voting-app
  name: postgres-deployment
spec: 
  replicas: 1
  selector:
   matchLabels: 
    name: postgres-pod
    app: demo-voting-app
  template: 
   metadata: 
    labels: 
      name: postgres-pod
      app: demo-voting-app
    name: postgres-pod
   spec: 
     containers: 
       - 
         image: postgres:9.4
         name: postgres
         ports:
          - containerPort: 5432
     