apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: demo-voting-app
  name: result-app-deployment
spec: 
  replicas: 1
  selector:
   matchLabels: 
    name: result-app-pod
    app: demo-voting-app
  template: 
   metadata: 
    labels: 
      name: result-app-pod
      app: demo-voting-app
    name: result-app-pod
   spec: 
     containers: 
       - 
         image: docker/example-voting-app-result
         name: result-app
         ports:
          - containerPort: 80
